In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
import warnings
warnings.filterwarnings(category=UserWarning,action='ignore', module="sklearn")
import pickle

In [ ]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [35]:

# Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
#        'Embarked'

# Pclass/sex/age/SibSp/Parch/Fare/Embarked

test_input = np.array([3, 'male', 35.0, 0, 0,8.0, 'S'],dtype=object).reshape(1,7)

test_input
#  xtest_final = np.concatenate((xtest_rem, xtest_embarked_encode, xtest_impute_age, xtest_sex_encode), axis=1)

array([[3, 'male', 35.0, 0, 0, 8.0, 'S']], dtype=object)

In [ ]:
test_input = np.array([3, 'female', 26.0, 0, 0,7.9250, 'S'],dtype=object).reshape(1,7)

test_input

In [36]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

array([[0., 1.]])

In [37]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [38]:
test_input_age = test_input[:,2].reshape(1,1)

In [39]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_embarked,test_input_age,test_input_sex,),axis=1)

In [40]:
test_input_transformed.shape

(1, 10)

In [42]:
clf.predict(test_input_transformed)

array([0])

In [43]:
clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}